//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attraction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attraction()
        {
            this.MaintenanceSchedule = new HashSet<MaintenanceSchedule>();
        }
    
        public int AttractionId { get; set; }
        public string AttractionName { get; set; }
        public string AttractionDescription { get; set; }
        public string AttractionHowToWork { get; set; }
        public string AttractionWhoParticipant { get; set; }
        public System.DateTime AttractionStartDateLaunch { get; set; }
        public string AttractionStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceSchedule> MaintenanceSchedule { get; set; }
    }
}
