//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelTransaction
    {
        public int HotelTransactionId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime HotelTransactionDate { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int RoomId { get; set; }
        public int VisitorId { get; set; }
        public Nullable<int> Payment { get; set; }
    
        public virtual RoomHotel RoomHotel { get; set; }
    }
}
