//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceSchedule
    {
        public int MaintenanceScheduleId { get; set; }
        public Nullable<int> RideId { get; set; }
        public Nullable<int> AttractionId { get; set; }
        public string RideName { get; set; }
        public string AttractionName { get; set; }
        public string MaintenanceNote { get; set; }
        public System.DateTime MaintenanceDate { get; set; }
        public string MaintenaceStartTime { get; set; }
        public string MaintenanceEndTime { get; set; }
    
        public virtual Attraction Attraction { get; set; }
        public virtual Ride Ride { get; set; }
    }
}
