//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int PurchaseOrderId { get; set; }
        public string WhoBuy { get; set; }
        public System.DateTime PurchaseOrderDate { get; set; }
        public int AmountPurchase { get; set; }
        public string PurchaseOrderStatus { get; set; }
    }
}
