//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestPurchase
    {
        public int RequestPurchaseId { get; set; }
        public int EmployeeId { get; set; }
        public string RequestPurchaseDetail { get; set; }
        public string RequestPurchaseStatus { get; set; }
        public System.DateTime RequestDateNeed { get; set; }
        public System.DateTime RequestPurchaseDate { get; set; }
        public string PurchaseTimeNeed { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
