//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestResign
    {
        public int RequestResignId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime AssignDate { get; set; }
        public string ResignReason { get; set; }
        public string ResignStatus { get; set; }
        public string ReasonManager { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
