//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestAttraction
    {
        public int ReqAttId { get; set; }
        public string ReqAttName { get; set; }
        public string ReqAttDescription { get; set; }
        public string ReqAttHowToWork { get; set; }
        public string ReqAttWhoParticipant { get; set; }
        public System.DateTime ReqAttStartDateLaunch { get; set; }
        public string ReqAttStatus { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> AttractionId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
