//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestFund
    {
        public int RequestFundId { get; set; }
        public int EmployeeId { get; set; }
        public string RequestFundDetail { get; set; }
        public string RequestFundStatus { get; set; }
        public int PredictedAmount { get; set; }
        public System.DateTime RequestFundDate { get; set; }
        public string RequestReason { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
