//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantTransaction
    {
        public int ResturantTransaction { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string OrderMethod { get; set; }
        public string NumberTable { get; set; }
        public string NameVisitor { get; set; }
        public string RestaurantTransactionStatus { get; set; }
        public Nullable<int> Payment { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
