//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderTheSea.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnderTheSeaDBsEntities : DbContext
    {
        public UnderTheSeaDBsEntities()
            : base("name=UnderTheSeaDBsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<Attraction> Attraction { get; set; }
        public virtual DbSet<Construction> Construction { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeDepartment> EmployeeDepartment { get; set; }
        public virtual DbSet<HotelTransaction> HotelTransaction { get; set; }
        public virtual DbSet<MaintenanceSchedule> MaintenanceSchedule { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<NumberTable> NumberTable { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual DbSet<RequestAttraction> RequestAttraction { get; set; }
        public virtual DbSet<RequestFund> RequestFund { get; set; }
        public virtual DbSet<RequestPermit> RequestPermit { get; set; }
        public virtual DbSet<RequestPurchase> RequestPurchase { get; set; }
        public virtual DbSet<RequestResign> RequestResign { get; set; }
        public virtual DbSet<RequestRide> RequestRide { get; set; }
        public virtual DbSet<RestaurantTransaction> RestaurantTransaction { get; set; }
        public virtual DbSet<Ride> Ride { get; set; }
        public virtual DbSet<RoomHotel> RoomHotel { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TicketTransaction> TicketTransaction { get; set; }
    }
}
